//! Auto-generated — instantiates every CASE/UCO struct to verify the object model.

use case_uco::case::investigation::Attorney;
use case_uco::case::investigation::Authorization;
use case_uco::case::investigation::Examiner;
use case_uco::case::investigation::Investigation;
use case_uco::case::investigation::InvestigativeAction;
use case_uco::case::investigation::Investigator;
use case_uco::case::investigation::ProvenanceRecord;
use case_uco::case::investigation::Subject;
use case_uco::case::investigation::SubjectActionLifecycle;
use case_uco::case::investigation::VictimActionLifecycle;
use case_uco::uco::action::Action;
use case_uco::uco::action::ActionArgumentFacet;
use case_uco::uco::action::ActionEstimationFacet;
use case_uco::uco::action::ActionFrequencyFacet;
use case_uco::uco::action::ActionLifecycle;
use case_uco::uco::action::ActionPattern;
use case_uco::uco::action::ArrayOfAction;
use case_uco::uco::analysis::AnalyticResultFacet;
use case_uco::uco::analysis::ArtifactClassification;
use case_uco::uco::analysis::ArtifactClassificationResultFacet;
use case_uco::uco::configuration::Configuration;
use case_uco::uco::configuration::ConfigurationEntry;
use case_uco::uco::configuration::Dependency;
use case_uco::uco::core::Annotation;
use case_uco::uco::core::Assertion;
use case_uco::uco::core::AttributedName;
use case_uco::uco::core::Bundle;
use case_uco::uco::core::Compilation;
use case_uco::uco::core::ConfidenceFacet;
use case_uco::uco::core::ContextualCompilation;
use case_uco::uco::core::ControlledVocabulary;
use case_uco::uco::core::EnclosingCompilation;
use case_uco::uco::core::Event;
use case_uco::uco::core::ExternalReference;
use case_uco::uco::core::Facet;
use case_uco::uco::core::Grouping;
use case_uco::uco::core::IdentityAbstraction;
use case_uco::uco::core::Item;
use case_uco::uco::core::MarkingDefinitionAbstraction;
use case_uco::uco::core::ModusOperandi;
use case_uco::uco::core::Relationship;
use case_uco::uco::core::UcoInherentCharacterizationThing;
use case_uco::uco::core::UcoObject;
use case_uco::uco::core::UcoThing;
use case_uco::uco::identity::AddressFacet;
use case_uco::uco::identity::AffiliationFacet;
use case_uco::uco::identity::BirthInformationFacet;
use case_uco::uco::identity::CountryOfResidenceFacet;
use case_uco::uco::identity::EventsFacet;
use case_uco::uco::identity::IdentifierFacet;
use case_uco::uco::identity::Identity;
use case_uco::uco::identity::IdentityFacet;
use case_uco::uco::identity::LanguagesFacet;
use case_uco::uco::identity::NationalityFacet;
use case_uco::uco::identity::OccupationFacet;
use case_uco::uco::identity::Organization;
use case_uco::uco::identity::OrganizationDetailsFacet;
use case_uco::uco::identity::Person;
use case_uco::uco::identity::PersonalDetailsFacet;
use case_uco::uco::identity::PhysicalInfoFacet;
use case_uco::uco::identity::QualificationFacet;
use case_uco::uco::identity::RelatedIdentityFacet;
use case_uco::uco::identity::SimpleNameFacet;
use case_uco::uco::identity::VisaFacet;
use case_uco::uco::location::GPSCoordinatesFacet;
use case_uco::uco::location::LatLongCoordinatesFacet;
use case_uco::uco::location::Location;
use case_uco::uco::location::SimpleAddressFacet;
use case_uco::uco::marking::GranularMarking;
use case_uco::uco::marking::LicenseMarking;
use case_uco::uco::marking::MarkingDefinition;
use case_uco::uco::marking::MarkingModel;
use case_uco::uco::marking::ReleaseToMarking;
use case_uco::uco::marking::StatementMarking;
use case_uco::uco::marking::TermsOfUseMarking;
use case_uco::uco::observable::API;
use case_uco::uco::observable::ARPCache;
use case_uco::uco::observable::ARPCacheEntry;
use case_uco::uco::observable::Account;
use case_uco::uco::observable::AccountAuthenticationFacet;
use case_uco::uco::observable::AccountFacet;
use case_uco::uco::observable::Adaptor;
use case_uco::uco::observable::Address;
use case_uco::uco::observable::AlternateDataStream;
use case_uco::uco::observable::AlternateDataStreamFacet;
use case_uco::uco::observable::AndroidDevice;
use case_uco::uco::observable::AndroidDeviceFacet;
use case_uco::uco::observable::AndroidPhone;
use case_uco::uco::observable::AntennaFacet;
use case_uco::uco::observable::AppleDevice;
use case_uco::uco::observable::Appliance;
use case_uco::uco::observable::Application;
use case_uco::uco::observable::ApplicationAccount;
use case_uco::uco::observable::ApplicationAccountFacet;
use case_uco::uco::observable::ApplicationFacet;
use case_uco::uco::observable::ApplicationVersion;
use case_uco::uco::observable::ArchiveFile;
use case_uco::uco::observable::ArchiveFileFacet;
use case_uco::uco::observable::Audio;
use case_uco::uco::observable::AudioFacet;
use case_uco::uco::observable::AutonomousSystem;
use case_uco::uco::observable::AutonomousSystemFacet;
use case_uco::uco::observable::BlackberryPhone;
use case_uco::uco::observable::BlockDeviceNode;
use case_uco::uco::observable::BluetoothAddress;
use case_uco::uco::observable::BluetoothAddressFacet;
use case_uco::uco::observable::BotConfiguration;
use case_uco::uco::observable::BrowserBookmark;
use case_uco::uco::observable::BrowserBookmarkFacet;
use case_uco::uco::observable::BrowserCookie;
use case_uco::uco::observable::BrowserCookieFacet;
use case_uco::uco::observable::Calendar;
use case_uco::uco::observable::CalendarEntry;
use case_uco::uco::observable::CalendarEntryFacet;
use case_uco::uco::observable::CalendarFacet;
use case_uco::uco::observable::Call;
use case_uco::uco::observable::CallFacet;
use case_uco::uco::observable::CapturedTelecommunicationsInformation;
use case_uco::uco::observable::CapturedTelecommunicationsInformationFacet;
use case_uco::uco::observable::CellSite;
use case_uco::uco::observable::CellSiteFacet;
use case_uco::uco::observable::CharacterDeviceNode;
use case_uco::uco::observable::Code;
use case_uco::uco::observable::CompressedStreamFacet;
use case_uco::uco::observable::Computer;
use case_uco::uco::observable::ComputerSpecification;
use case_uco::uco::observable::ComputerSpecificationFacet;
use case_uco::uco::observable::ConfiguredSoftware;
use case_uco::uco::observable::Contact;
use case_uco::uco::observable::ContactAddress;
use case_uco::uco::observable::ContactAffiliation;
use case_uco::uco::observable::ContactEmail;
use case_uco::uco::observable::ContactFacet;
use case_uco::uco::observable::ContactList;
use case_uco::uco::observable::ContactListFacet;
use case_uco::uco::observable::ContactMessaging;
use case_uco::uco::observable::ContactPhone;
use case_uco::uco::observable::ContactProfile;
use case_uco::uco::observable::ContactSIP;
use case_uco::uco::observable::ContactURL;
use case_uco::uco::observable::ContentData;
use case_uco::uco::observable::ContentDataFacet;
use case_uco::uco::observable::CookieHistory;
use case_uco::uco::observable::Credential;
use case_uco::uco::observable::CredentialDump;
use case_uco::uco::observable::DNSCache;
use case_uco::uco::observable::DNSRecord;
use case_uco::uco::observable::DataRangeFacet;
use case_uco::uco::observable::DefinedEffectFacet;
use case_uco::uco::observable::Device;
use case_uco::uco::observable::DeviceFacet;
use case_uco::uco::observable::DigitalAccount;
use case_uco::uco::observable::DigitalAccountFacet;
use case_uco::uco::observable::DigitalAddress;
use case_uco::uco::observable::DigitalAddressFacet;
use case_uco::uco::observable::DigitalCamera;
use case_uco::uco::observable::DigitalSignatureInfo;
use case_uco::uco::observable::DigitalSignatureInfoFacet;
use case_uco::uco::observable::Directory;
use case_uco::uco::observable::Disk;
use case_uco::uco::observable::DiskFacet;
use case_uco::uco::observable::DiskPartition;
use case_uco::uco::observable::DiskPartitionFacet;
use case_uco::uco::observable::DomainName;
use case_uco::uco::observable::DomainNameFacet;
use case_uco::uco::observable::Drone;
use case_uco::uco::observable::EXIFFacet;
use case_uco::uco::observable::EmailAccount;
use case_uco::uco::observable::EmailAccountFacet;
use case_uco::uco::observable::EmailAddress;
use case_uco::uco::observable::EmailAddressFacet;
use case_uco::uco::observable::EmailMessage;
use case_uco::uco::observable::EmailMessageFacet;
use case_uco::uco::observable::EmbeddedDevice;
use case_uco::uco::observable::EncodedStreamFacet;
use case_uco::uco::observable::EncryptedStreamFacet;
use case_uco::uco::observable::EnvironmentVariable;
use case_uco::uco::observable::EventLog;
use case_uco::uco::observable::EventRecord;
use case_uco::uco::observable::EventRecordFacet;
use case_uco::uco::observable::ExtInodeFacet;
use case_uco::uco::observable::ExtractedString;
use case_uco::uco::observable::ExtractedStringsFacet;
use case_uco::uco::observable::File;
use case_uco::uco::observable::FileFacet;
use case_uco::uco::observable::FilePermissionsFacet;
use case_uco::uco::observable::FileSystem;
use case_uco::uco::observable::FileSystemFacet;
use case_uco::uco::observable::FileSystemObject;
use case_uco::uco::observable::ForumPost;
use case_uco::uco::observable::ForumPrivateMessage;
use case_uco::uco::observable::FragmentFacet;
use case_uco::uco::observable::GUI;
use case_uco::uco::observable::GamingConsole;
use case_uco::uco::observable::GenericObservableObject;
use case_uco::uco::observable::GeoLocationEntry;
use case_uco::uco::observable::GeoLocationEntryFacet;
use case_uco::uco::observable::GeoLocationLog;
use case_uco::uco::observable::GeoLocationLogFacet;
use case_uco::uco::observable::GeoLocationTrack;
use case_uco::uco::observable::GeoLocationTrackFacet;
use case_uco::uco::observable::GlobalFlagType;
use case_uco::uco::observable::HTTPConnection;
use case_uco::uco::observable::HTTPConnectionFacet;
use case_uco::uco::observable::Hostname;
use case_uco::uco::observable::ICMPConnection;
use case_uco::uco::observable::ICMPConnectionFacet;
use case_uco::uco::observable::IComHandlerActionType;
use case_uco::uco::observable::IExecActionType;
use case_uco::uco::observable::IPAddress;
use case_uco::uco::observable::IPAddressFacet;
use case_uco::uco::observable::IPNetmask;
use case_uco::uco::observable::IPhone;
use case_uco::uco::observable::IPv4Address;
use case_uco::uco::observable::IPv4AddressFacet;
use case_uco::uco::observable::IPv6Address;
use case_uco::uco::observable::IPv6AddressFacet;
use case_uco::uco::observable::IShowMessageActionType;
use case_uco::uco::observable::Image;
use case_uco::uco::observable::ImageFacet;
use case_uco::uco::observable::InstantMessagingAddress;
use case_uco::uco::observable::InstantMessagingAddressFacet;
use case_uco::uco::observable::Junction;
use case_uco::uco::observable::Laptop;
use case_uco::uco::observable::Library;
use case_uco::uco::observable::LibraryFacet;
use case_uco::uco::observable::MACAddress;
use case_uco::uco::observable::MACAddressFacet;
use case_uco::uco::observable::Memory;
use case_uco::uco::observable::MemoryFacet;
use case_uco::uco::observable::Message;
use case_uco::uco::observable::MessageFacet;
use case_uco::uco::observable::MessageThread;
use case_uco::uco::observable::MessageThreadFacet;
use case_uco::uco::observable::MftRecordFacet;
use case_uco::uco::observable::MimePartType;
use case_uco::uco::observable::MobileAccount;
use case_uco::uco::observable::MobileAccountFacet;
use case_uco::uco::observable::MobileDevice;
use case_uco::uco::observable::MobileDeviceFacet;
use case_uco::uco::observable::MobilePhone;
use case_uco::uco::observable::Mutex;
use case_uco::uco::observable::MutexFacet;
use case_uco::uco::observable::NTFSFile;
use case_uco::uco::observable::NTFSFileFacet;
use case_uco::uco::observable::NTFSFilePermissionsFacet;
use case_uco::uco::observable::NamedPipe;
use case_uco::uco::observable::NetworkAppliance;
use case_uco::uco::observable::NetworkConnection;
use case_uco::uco::observable::NetworkConnectionFacet;
use case_uco::uco::observable::NetworkFlow;
use case_uco::uco::observable::NetworkFlowFacet;
use case_uco::uco::observable::NetworkInterface;
use case_uco::uco::observable::NetworkInterfaceFacet;
use case_uco::uco::observable::NetworkProtocol;
use case_uco::uco::observable::NetworkRoute;
use case_uco::uco::observable::NetworkSubnet;
use case_uco::uco::observable::Note;
use case_uco::uco::observable::NoteFacet;
use case_uco::uco::observable::Observable;
use case_uco::uco::observable::ObservableAction;
use case_uco::uco::observable::ObservableObject;
use case_uco::uco::observable::ObservablePattern;
use case_uco::uco::observable::ObservableRelationship;
use case_uco::uco::observable::Observation;
use case_uco::uco::observable::OnlineService;
use case_uco::uco::observable::OnlineServiceFacet;
use case_uco::uco::observable::OperatingSystem;
use case_uco::uco::observable::OperatingSystemFacet;
use case_uco::uco::observable::PDFFile;
use case_uco::uco::observable::PDFFileFacet;
use case_uco::uco::observable::PathRelationFacet;
use case_uco::uco::observable::PaymentCard;
use case_uco::uco::observable::PhoneAccount;
use case_uco::uco::observable::PhoneAccountFacet;
use case_uco::uco::observable::Pipe;
use case_uco::uco::observable::Post;
use case_uco::uco::observable::Process;
use case_uco::uco::observable::ProcessFacet;
use case_uco::uco::observable::ProcessThread;
use case_uco::uco::observable::Profile;
use case_uco::uco::observable::ProfileFacet;
use case_uco::uco::observable::PropertiesEnumeratedEffectFacet;
use case_uco::uco::observable::PropertyReadEffectFacet;
use case_uco::uco::observable::ProtocolConverter;
use case_uco::uco::observable::RasterPicture;
use case_uco::uco::observable::RasterPictureFacet;
use case_uco::uco::observable::RecoveredObject;
use case_uco::uco::observable::RecoveredObjectFacet;
use case_uco::uco::observable::ReparsePoint;
use case_uco::uco::observable::SIMCard;
use case_uco::uco::observable::SIMCardFacet;
use case_uco::uco::observable::SIPAddress;
use case_uco::uco::observable::SIPAddressFacet;
use case_uco::uco::observable::SMSMessage;
use case_uco::uco::observable::SMSMessageFacet;
use case_uco::uco::observable::SQLiteBlob;
use case_uco::uco::observable::SQLiteBlobFacet;
use case_uco::uco::observable::SecurityAppliance;
use case_uco::uco::observable::Semaphore;
use case_uco::uco::observable::SendControlCodeEffectFacet;
use case_uco::uco::observable::Server;
use case_uco::uco::observable::ShopListing;
use case_uco::uco::observable::SmartDevice;
use case_uco::uco::observable::SmartPhone;
use case_uco::uco::observable::Snapshot;
use case_uco::uco::observable::Socket;
use case_uco::uco::observable::SocketAddress;
use case_uco::uco::observable::Software;
use case_uco::uco::observable::SoftwareFacet;
use case_uco::uco::observable::StateChangeEffectFacet;
use case_uco::uco::observable::StorageMedium;
use case_uco::uco::observable::StorageMediumFacet;
use case_uco::uco::observable::SymbolicLink;
use case_uco::uco::observable::SymbolicLinkFacet;
use case_uco::uco::observable::TCPConnection;
use case_uco::uco::observable::TCPConnectionFacet;
use case_uco::uco::observable::TableField;
use case_uco::uco::observable::TableFieldFacet;
use case_uco::uco::observable::Tablet;
use case_uco::uco::observable::TaskActionType;
use case_uco::uco::observable::TriggerType;
use case_uco::uco::observable::Tweet;
use case_uco::uco::observable::TwitterProfileFacet;
use case_uco::uco::observable::UNIXAccount;
use case_uco::uco::observable::UNIXAccountFacet;
use case_uco::uco::observable::UNIXFile;
use case_uco::uco::observable::UNIXFilePermissionsFacet;
use case_uco::uco::observable::UNIXProcess;
use case_uco::uco::observable::UNIXProcessFacet;
use case_uco::uco::observable::UNIXVolumeFacet;
use case_uco::uco::observable::URL;
use case_uco::uco::observable::URLFacet;
use case_uco::uco::observable::URLHistory;
use case_uco::uco::observable::URLHistoryEntry;
use case_uco::uco::observable::URLHistoryFacet;
use case_uco::uco::observable::URLVisit;
use case_uco::uco::observable::URLVisitFacet;
use case_uco::uco::observable::UserAccount;
use case_uco::uco::observable::UserAccountFacet;
use case_uco::uco::observable::UserSession;
use case_uco::uco::observable::UserSessionFacet;
use case_uco::uco::observable::ValuesEnumeratedEffectFacet;
use case_uco::uco::observable::Volume;
use case_uco::uco::observable::VolumeFacet;
use case_uco::uco::observable::WearableDevice;
use case_uco::uco::observable::WebPage;
use case_uco::uco::observable::WhoIs;
use case_uco::uco::observable::WhoIsFacet;
use case_uco::uco::observable::WhoisContactFacet;
use case_uco::uco::observable::WhoisRegistrarInfoType;
use case_uco::uco::observable::WifiAddress;
use case_uco::uco::observable::WifiAddressFacet;
use case_uco::uco::observable::Wiki;
use case_uco::uco::observable::WikiArticle;
use case_uco::uco::observable::WindowsAccount;
use case_uco::uco::observable::WindowsAccountFacet;
use case_uco::uco::observable::WindowsActiveDirectoryAccount;
use case_uco::uco::observable::WindowsActiveDirectoryAccountFacet;
use case_uco::uco::observable::WindowsComputerSpecification;
use case_uco::uco::observable::WindowsComputerSpecificationFacet;
use case_uco::uco::observable::WindowsCriticalSection;
use case_uco::uco::observable::WindowsEvent;
use case_uco::uco::observable::WindowsFilemapping;
use case_uco::uco::observable::WindowsHandle;
use case_uco::uco::observable::WindowsHook;
use case_uco::uco::observable::WindowsMailslot;
use case_uco::uco::observable::WindowsNetworkShare;
use case_uco::uco::observable::WindowsPEBinaryFile;
use case_uco::uco::observable::WindowsPEBinaryFileFacet;
use case_uco::uco::observable::WindowsPEFileHeader;
use case_uco::uco::observable::WindowsPEOptionalHeader;
use case_uco::uco::observable::WindowsPESection;
use case_uco::uco::observable::WindowsPrefetch;
use case_uco::uco::observable::WindowsPrefetchFacet;
use case_uco::uco::observable::WindowsProcess;
use case_uco::uco::observable::WindowsProcessFacet;
use case_uco::uco::observable::WindowsRegistryHive;
use case_uco::uco::observable::WindowsRegistryHiveFacet;
use case_uco::uco::observable::WindowsRegistryKey;
use case_uco::uco::observable::WindowsRegistryKeyFacet;
use case_uco::uco::observable::WindowsRegistryValue;
use case_uco::uco::observable::WindowsService;
use case_uco::uco::observable::WindowsServiceFacet;
use case_uco::uco::observable::WindowsSystemRestore;
use case_uco::uco::observable::WindowsTask;
use case_uco::uco::observable::WindowsTaskFacet;
use case_uco::uco::observable::WindowsThread;
use case_uco::uco::observable::WindowsThreadFacet;
use case_uco::uco::observable::WindowsVolumeFacet;
use case_uco::uco::observable::WindowsWaitableTime;
use case_uco::uco::observable::WirelessNetworkConnection;
use case_uco::uco::observable::WirelessNetworkConnectionFacet;
use case_uco::uco::observable::WriteBlocker;
use case_uco::uco::observable::X509Certificate;
use case_uco::uco::observable::X509CertificateFacet;
use case_uco::uco::observable::X509V3Certificate;
use case_uco::uco::observable::X509V3ExtensionsFacet;
use case_uco::uco::pattern::LogicalPattern;
use case_uco::uco::pattern::Pattern;
use case_uco::uco::pattern::PatternExpression;
use case_uco::uco::role::BenevolentRole;
use case_uco::uco::role::MaliciousRole;
use case_uco::uco::role::NeutralRole;
use case_uco::uco::role::Role;
use case_uco::uco::tool::AnalyticTool;
use case_uco::uco::tool::BuildFacet;
use case_uco::uco::tool::BuildInformationType;
use case_uco::uco::tool::BuildUtilityType;
use case_uco::uco::tool::CompilerType;
use case_uco::uco::tool::ConfiguredTool;
use case_uco::uco::tool::DefensiveTool;
use case_uco::uco::tool::LibraryType;
use case_uco::uco::tool::MaliciousTool;
use case_uco::uco::tool::Tool;
use case_uco::uco::types::ControlledDictionary;
use case_uco::uco::types::ControlledDictionaryEntry;
use case_uco::uco::types::Dictionary;
use case_uco::uco::types::DictionaryEntry;
use case_uco::uco::types::Hash;
use case_uco::uco::types::ImproperDictionary;
use case_uco::uco::types::ProperDictionary;
use case_uco::uco::types::Thread;
use case_uco::uco::types::ThreadItem;
use case_uco::uco::victim::Victim;
use case_uco::uco::victim::VictimTargeting;

#[test]
fn test_all_classes_can_be_instantiated() {
    let mut instances: Vec<Box<dyn std::fmt::Debug>> = Vec::new();
    instances.push(Box::new(Attorney::builder().build()));
    instances.push(Box::new(Authorization::builder().build()));
    instances.push(Box::new(Examiner::builder().build()));
    instances.push(Box::new(Investigation::builder().build()));
    instances.push(Box::new(InvestigativeAction::builder().build()));
    instances.push(Box::new(Investigator::builder().build()));
    instances.push(Box::new(ProvenanceRecord::builder().build()));
    instances.push(Box::new(Subject::builder().build()));
    instances.push(Box::new(SubjectActionLifecycle::builder().build()));
    instances.push(Box::new(VictimActionLifecycle::builder().build()));
    instances.push(Box::new(Action::builder().build()));
    instances.push(Box::new(ActionArgumentFacet::builder().build()));
    instances.push(Box::new(ActionEstimationFacet::builder().build()));
    instances.push(Box::new(ActionFrequencyFacet::builder().build()));
    instances.push(Box::new(ActionLifecycle::builder().build()));
    instances.push(Box::new(ActionPattern::builder().build()));
    instances.push(Box::new(ArrayOfAction::builder().build()));
    instances.push(Box::new(AnalyticResultFacet::builder().build()));
    instances.push(Box::new(ArtifactClassification::builder().build()));
    instances.push(Box::new(ArtifactClassificationResultFacet::builder().build()));
    instances.push(Box::new(Configuration::builder().build()));
    instances.push(Box::new(ConfigurationEntry::builder().build()));
    instances.push(Box::new(Dependency::builder().build()));
    instances.push(Box::new(Annotation::builder().build()));
    instances.push(Box::new(Assertion::builder().build()));
    instances.push(Box::new(AttributedName::builder().build()));
    instances.push(Box::new(Bundle::builder().build()));
    instances.push(Box::new(Compilation::builder().build()));
    instances.push(Box::new(ConfidenceFacet::builder().build()));
    instances.push(Box::new(ContextualCompilation::builder().build()));
    instances.push(Box::new(ControlledVocabulary::builder().build()));
    instances.push(Box::new(EnclosingCompilation::builder().build()));
    instances.push(Box::new(Event::builder().build()));
    instances.push(Box::new(ExternalReference::builder().build()));
    instances.push(Box::new(Facet::builder().build()));
    instances.push(Box::new(Grouping::builder().build()));
    instances.push(Box::new(IdentityAbstraction::builder().build()));
    instances.push(Box::new(Item::builder().build()));
    instances.push(Box::new(MarkingDefinitionAbstraction::builder().build()));
    instances.push(Box::new(ModusOperandi::builder().build()));
    instances.push(Box::new(Relationship::builder().build()));
    instances.push(Box::new(UcoInherentCharacterizationThing::builder().build()));
    instances.push(Box::new(UcoObject::builder().build()));
    instances.push(Box::new(UcoThing::builder().build()));
    instances.push(Box::new(AddressFacet::builder().build()));
    instances.push(Box::new(AffiliationFacet::builder().build()));
    instances.push(Box::new(BirthInformationFacet::builder().build()));
    instances.push(Box::new(CountryOfResidenceFacet::builder().build()));
    instances.push(Box::new(EventsFacet::builder().build()));
    instances.push(Box::new(IdentifierFacet::builder().build()));
    instances.push(Box::new(Identity::builder().build()));
    instances.push(Box::new(IdentityFacet::builder().build()));
    instances.push(Box::new(LanguagesFacet::builder().build()));
    instances.push(Box::new(NationalityFacet::builder().build()));
    instances.push(Box::new(OccupationFacet::builder().build()));
    instances.push(Box::new(Organization::builder().build()));
    instances.push(Box::new(OrganizationDetailsFacet::builder().build()));
    instances.push(Box::new(Person::builder().build()));
    instances.push(Box::new(PersonalDetailsFacet::builder().build()));
    instances.push(Box::new(PhysicalInfoFacet::builder().build()));
    instances.push(Box::new(QualificationFacet::builder().build()));
    instances.push(Box::new(RelatedIdentityFacet::builder().build()));
    instances.push(Box::new(SimpleNameFacet::builder().build()));
    instances.push(Box::new(VisaFacet::builder().build()));
    instances.push(Box::new(GPSCoordinatesFacet::builder().build()));
    instances.push(Box::new(LatLongCoordinatesFacet::builder().build()));
    instances.push(Box::new(Location::builder().build()));
    instances.push(Box::new(SimpleAddressFacet::builder().build()));
    instances.push(Box::new(GranularMarking::builder().build()));
    instances.push(Box::new(LicenseMarking::builder().build()));
    instances.push(Box::new(MarkingDefinition::builder().build()));
    instances.push(Box::new(MarkingModel::builder().build()));
    instances.push(Box::new(ReleaseToMarking::builder().build()));
    instances.push(Box::new(StatementMarking::builder().build()));
    instances.push(Box::new(TermsOfUseMarking::builder().build()));
    instances.push(Box::new(API::builder().build()));
    instances.push(Box::new(ARPCache::builder().build()));
    instances.push(Box::new(ARPCacheEntry::builder().build()));
    instances.push(Box::new(Account::builder().build()));
    instances.push(Box::new(AccountAuthenticationFacet::builder().build()));
    instances.push(Box::new(AccountFacet::builder().build()));
    instances.push(Box::new(Adaptor::builder().build()));
    instances.push(Box::new(Address::builder().build()));
    instances.push(Box::new(AlternateDataStream::builder().build()));
    instances.push(Box::new(AlternateDataStreamFacet::builder().build()));
    instances.push(Box::new(AndroidDevice::builder().build()));
    instances.push(Box::new(AndroidDeviceFacet::builder().build()));
    instances.push(Box::new(AndroidPhone::builder().build()));
    instances.push(Box::new(AntennaFacet::builder().build()));
    instances.push(Box::new(AppleDevice::builder().build()));
    instances.push(Box::new(Appliance::builder().build()));
    instances.push(Box::new(Application::builder().build()));
    instances.push(Box::new(ApplicationAccount::builder().build()));
    instances.push(Box::new(ApplicationAccountFacet::builder().build()));
    instances.push(Box::new(ApplicationFacet::builder().build()));
    instances.push(Box::new(ApplicationVersion::builder().build()));
    instances.push(Box::new(ArchiveFile::builder().build()));
    instances.push(Box::new(ArchiveFileFacet::builder().build()));
    instances.push(Box::new(Audio::builder().build()));
    instances.push(Box::new(AudioFacet::builder().build()));
    instances.push(Box::new(AutonomousSystem::builder().build()));
    instances.push(Box::new(AutonomousSystemFacet::builder().build()));
    instances.push(Box::new(BlackberryPhone::builder().build()));
    instances.push(Box::new(BlockDeviceNode::builder().build()));
    instances.push(Box::new(BluetoothAddress::builder().build()));
    instances.push(Box::new(BluetoothAddressFacet::builder().build()));
    instances.push(Box::new(BotConfiguration::builder().build()));
    instances.push(Box::new(BrowserBookmark::builder().build()));
    instances.push(Box::new(BrowserBookmarkFacet::builder().build()));
    instances.push(Box::new(BrowserCookie::builder().build()));
    instances.push(Box::new(BrowserCookieFacet::builder().build()));
    instances.push(Box::new(Calendar::builder().build()));
    instances.push(Box::new(CalendarEntry::builder().build()));
    instances.push(Box::new(CalendarEntryFacet::builder().build()));
    instances.push(Box::new(CalendarFacet::builder().build()));
    instances.push(Box::new(Call::builder().build()));
    instances.push(Box::new(CallFacet::builder().build()));
    instances.push(Box::new(CapturedTelecommunicationsInformation::builder().build()));
    instances.push(Box::new(CapturedTelecommunicationsInformationFacet::builder().build()));
    instances.push(Box::new(CellSite::builder().build()));
    instances.push(Box::new(CellSiteFacet::builder().build()));
    instances.push(Box::new(CharacterDeviceNode::builder().build()));
    instances.push(Box::new(Code::builder().build()));
    instances.push(Box::new(CompressedStreamFacet::builder().build()));
    instances.push(Box::new(Computer::builder().build()));
    instances.push(Box::new(ComputerSpecification::builder().build()));
    instances.push(Box::new(ComputerSpecificationFacet::builder().build()));
    instances.push(Box::new(ConfiguredSoftware::builder().build()));
    instances.push(Box::new(Contact::builder().build()));
    instances.push(Box::new(ContactAddress::builder().build()));
    instances.push(Box::new(ContactAffiliation::builder().build()));
    instances.push(Box::new(ContactEmail::builder().build()));
    instances.push(Box::new(ContactFacet::builder().build()));
    instances.push(Box::new(ContactList::builder().build()));
    instances.push(Box::new(ContactListFacet::builder().build()));
    instances.push(Box::new(ContactMessaging::builder().build()));
    instances.push(Box::new(ContactPhone::builder().build()));
    instances.push(Box::new(ContactProfile::builder().build()));
    instances.push(Box::new(ContactSIP::builder().build()));
    instances.push(Box::new(ContactURL::builder().build()));
    instances.push(Box::new(ContentData::builder().build()));
    instances.push(Box::new(ContentDataFacet::builder().build()));
    instances.push(Box::new(CookieHistory::builder().build()));
    instances.push(Box::new(Credential::builder().build()));
    instances.push(Box::new(CredentialDump::builder().build()));
    instances.push(Box::new(DNSCache::builder().build()));
    instances.push(Box::new(DNSRecord::builder().build()));
    instances.push(Box::new(DataRangeFacet::builder().build()));
    instances.push(Box::new(DefinedEffectFacet::builder().build()));
    instances.push(Box::new(Device::builder().build()));
    instances.push(Box::new(DeviceFacet::builder().build()));
    instances.push(Box::new(DigitalAccount::builder().build()));
    instances.push(Box::new(DigitalAccountFacet::builder().build()));
    instances.push(Box::new(DigitalAddress::builder().build()));
    instances.push(Box::new(DigitalAddressFacet::builder().build()));
    instances.push(Box::new(DigitalCamera::builder().build()));
    instances.push(Box::new(DigitalSignatureInfo::builder().build()));
    instances.push(Box::new(DigitalSignatureInfoFacet::builder().build()));
    instances.push(Box::new(Directory::builder().build()));
    instances.push(Box::new(Disk::builder().build()));
    instances.push(Box::new(DiskFacet::builder().build()));
    instances.push(Box::new(DiskPartition::builder().build()));
    instances.push(Box::new(DiskPartitionFacet::builder().build()));
    instances.push(Box::new(DomainName::builder().build()));
    instances.push(Box::new(DomainNameFacet::builder().build()));
    instances.push(Box::new(Drone::builder().build()));
    instances.push(Box::new(EXIFFacet::builder().build()));
    instances.push(Box::new(EmailAccount::builder().build()));
    instances.push(Box::new(EmailAccountFacet::builder().build()));
    instances.push(Box::new(EmailAddress::builder().build()));
    instances.push(Box::new(EmailAddressFacet::builder().build()));
    instances.push(Box::new(EmailMessage::builder().build()));
    instances.push(Box::new(EmailMessageFacet::builder().build()));
    instances.push(Box::new(EmbeddedDevice::builder().build()));
    instances.push(Box::new(EncodedStreamFacet::builder().build()));
    instances.push(Box::new(EncryptedStreamFacet::builder().build()));
    instances.push(Box::new(EnvironmentVariable::builder().build()));
    instances.push(Box::new(EventLog::builder().build()));
    instances.push(Box::new(EventRecord::builder().build()));
    instances.push(Box::new(EventRecordFacet::builder().build()));
    instances.push(Box::new(ExtInodeFacet::builder().build()));
    instances.push(Box::new(ExtractedString::builder().build()));
    instances.push(Box::new(ExtractedStringsFacet::builder().build()));
    instances.push(Box::new(File::builder().build()));
    instances.push(Box::new(FileFacet::builder().build()));
    instances.push(Box::new(FilePermissionsFacet::builder().build()));
    instances.push(Box::new(FileSystem::builder().build()));
    instances.push(Box::new(FileSystemFacet::builder().build()));
    instances.push(Box::new(FileSystemObject::builder().build()));
    instances.push(Box::new(ForumPost::builder().build()));
    instances.push(Box::new(ForumPrivateMessage::builder().build()));
    instances.push(Box::new(FragmentFacet::builder().build()));
    instances.push(Box::new(GUI::builder().build()));
    instances.push(Box::new(GamingConsole::builder().build()));
    instances.push(Box::new(GenericObservableObject::builder().build()));
    instances.push(Box::new(GeoLocationEntry::builder().build()));
    instances.push(Box::new(GeoLocationEntryFacet::builder().build()));
    instances.push(Box::new(GeoLocationLog::builder().build()));
    instances.push(Box::new(GeoLocationLogFacet::builder().build()));
    instances.push(Box::new(GeoLocationTrack::builder().build()));
    instances.push(Box::new(GeoLocationTrackFacet::builder().build()));
    instances.push(Box::new(GlobalFlagType::builder().build()));
    instances.push(Box::new(HTTPConnection::builder().build()));
    instances.push(Box::new(HTTPConnectionFacet::builder().build()));
    instances.push(Box::new(Hostname::builder().build()));
    instances.push(Box::new(ICMPConnection::builder().build()));
    instances.push(Box::new(ICMPConnectionFacet::builder().build()));
    instances.push(Box::new(IComHandlerActionType::builder().build()));
    instances.push(Box::new(IExecActionType::builder().build()));
    instances.push(Box::new(IPAddress::builder().build()));
    instances.push(Box::new(IPAddressFacet::builder().build()));
    instances.push(Box::new(IPNetmask::builder().build()));
    instances.push(Box::new(IPhone::builder().build()));
    instances.push(Box::new(IPv4Address::builder().build()));
    instances.push(Box::new(IPv4AddressFacet::builder().build()));
    instances.push(Box::new(IPv6Address::builder().build()));
    instances.push(Box::new(IPv6AddressFacet::builder().build()));
    instances.push(Box::new(IShowMessageActionType::builder().build()));
    instances.push(Box::new(Image::builder().build()));
    instances.push(Box::new(ImageFacet::builder().build()));
    instances.push(Box::new(InstantMessagingAddress::builder().build()));
    instances.push(Box::new(InstantMessagingAddressFacet::builder().build()));
    instances.push(Box::new(Junction::builder().build()));
    instances.push(Box::new(Laptop::builder().build()));
    instances.push(Box::new(Library::builder().build()));
    instances.push(Box::new(LibraryFacet::builder().build()));
    instances.push(Box::new(MACAddress::builder().build()));
    instances.push(Box::new(MACAddressFacet::builder().build()));
    instances.push(Box::new(Memory::builder().build()));
    instances.push(Box::new(MemoryFacet::builder().build()));
    instances.push(Box::new(Message::builder().build()));
    instances.push(Box::new(MessageFacet::builder().build()));
    instances.push(Box::new(MessageThread::builder().build()));
    instances.push(Box::new(MessageThreadFacet::builder().build()));
    instances.push(Box::new(MftRecordFacet::builder().build()));
    instances.push(Box::new(MimePartType::builder().build()));
    instances.push(Box::new(MobileAccount::builder().build()));
    instances.push(Box::new(MobileAccountFacet::builder().build()));
    instances.push(Box::new(MobileDevice::builder().build()));
    instances.push(Box::new(MobileDeviceFacet::builder().build()));
    instances.push(Box::new(MobilePhone::builder().build()));
    instances.push(Box::new(Mutex::builder().build()));
    instances.push(Box::new(MutexFacet::builder().build()));
    instances.push(Box::new(NTFSFile::builder().build()));
    instances.push(Box::new(NTFSFileFacet::builder().build()));
    instances.push(Box::new(NTFSFilePermissionsFacet::builder().build()));
    instances.push(Box::new(NamedPipe::builder().build()));
    instances.push(Box::new(NetworkAppliance::builder().build()));
    instances.push(Box::new(NetworkConnection::builder().build()));
    instances.push(Box::new(NetworkConnectionFacet::builder().build()));
    instances.push(Box::new(NetworkFlow::builder().build()));
    instances.push(Box::new(NetworkFlowFacet::builder().build()));
    instances.push(Box::new(NetworkInterface::builder().build()));
    instances.push(Box::new(NetworkInterfaceFacet::builder().build()));
    instances.push(Box::new(NetworkProtocol::builder().build()));
    instances.push(Box::new(NetworkRoute::builder().build()));
    instances.push(Box::new(NetworkSubnet::builder().build()));
    instances.push(Box::new(Note::builder().build()));
    instances.push(Box::new(NoteFacet::builder().build()));
    instances.push(Box::new(Observable::builder().build()));
    instances.push(Box::new(ObservableAction::builder().build()));
    instances.push(Box::new(ObservableObject::builder().build()));
    instances.push(Box::new(ObservablePattern::builder().build()));
    instances.push(Box::new(ObservableRelationship::builder().build()));
    instances.push(Box::new(Observation::builder().build()));
    instances.push(Box::new(OnlineService::builder().build()));
    instances.push(Box::new(OnlineServiceFacet::builder().build()));
    instances.push(Box::new(OperatingSystem::builder().build()));
    instances.push(Box::new(OperatingSystemFacet::builder().build()));
    instances.push(Box::new(PDFFile::builder().build()));
    instances.push(Box::new(PDFFileFacet::builder().build()));
    instances.push(Box::new(PathRelationFacet::builder().build()));
    instances.push(Box::new(PaymentCard::builder().build()));
    instances.push(Box::new(PhoneAccount::builder().build()));
    instances.push(Box::new(PhoneAccountFacet::builder().build()));
    instances.push(Box::new(Pipe::builder().build()));
    instances.push(Box::new(Post::builder().build()));
    instances.push(Box::new(Process::builder().build()));
    instances.push(Box::new(ProcessFacet::builder().build()));
    instances.push(Box::new(ProcessThread::builder().build()));
    instances.push(Box::new(Profile::builder().build()));
    instances.push(Box::new(ProfileFacet::builder().build()));
    instances.push(Box::new(PropertiesEnumeratedEffectFacet::builder().build()));
    instances.push(Box::new(PropertyReadEffectFacet::builder().build()));
    instances.push(Box::new(ProtocolConverter::builder().build()));
    instances.push(Box::new(RasterPicture::builder().build()));
    instances.push(Box::new(RasterPictureFacet::builder().build()));
    instances.push(Box::new(RecoveredObject::builder().build()));
    instances.push(Box::new(RecoveredObjectFacet::builder().build()));
    instances.push(Box::new(ReparsePoint::builder().build()));
    instances.push(Box::new(SIMCard::builder().build()));
    instances.push(Box::new(SIMCardFacet::builder().build()));
    instances.push(Box::new(SIPAddress::builder().build()));
    instances.push(Box::new(SIPAddressFacet::builder().build()));
    instances.push(Box::new(SMSMessage::builder().build()));
    instances.push(Box::new(SMSMessageFacet::builder().build()));
    instances.push(Box::new(SQLiteBlob::builder().build()));
    instances.push(Box::new(SQLiteBlobFacet::builder().build()));
    instances.push(Box::new(SecurityAppliance::builder().build()));
    instances.push(Box::new(Semaphore::builder().build()));
    instances.push(Box::new(SendControlCodeEffectFacet::builder().build()));
    instances.push(Box::new(Server::builder().build()));
    instances.push(Box::new(ShopListing::builder().build()));
    instances.push(Box::new(SmartDevice::builder().build()));
    instances.push(Box::new(SmartPhone::builder().build()));
    instances.push(Box::new(Snapshot::builder().build()));
    instances.push(Box::new(Socket::builder().build()));
    instances.push(Box::new(SocketAddress::builder().build()));
    instances.push(Box::new(Software::builder().build()));
    instances.push(Box::new(SoftwareFacet::builder().build()));
    instances.push(Box::new(StateChangeEffectFacet::builder().build()));
    instances.push(Box::new(StorageMedium::builder().build()));
    instances.push(Box::new(StorageMediumFacet::builder().build()));
    instances.push(Box::new(SymbolicLink::builder().build()));
    instances.push(Box::new(SymbolicLinkFacet::builder().build()));
    instances.push(Box::new(TCPConnection::builder().build()));
    instances.push(Box::new(TCPConnectionFacet::builder().build()));
    instances.push(Box::new(TableField::builder().build()));
    instances.push(Box::new(TableFieldFacet::builder().build()));
    instances.push(Box::new(Tablet::builder().build()));
    instances.push(Box::new(TaskActionType::builder().build()));
    instances.push(Box::new(TriggerType::builder().build()));
    instances.push(Box::new(Tweet::builder().build()));
    instances.push(Box::new(TwitterProfileFacet::builder().build()));
    instances.push(Box::new(UNIXAccount::builder().build()));
    instances.push(Box::new(UNIXAccountFacet::builder().build()));
    instances.push(Box::new(UNIXFile::builder().build()));
    instances.push(Box::new(UNIXFilePermissionsFacet::builder().build()));
    instances.push(Box::new(UNIXProcess::builder().build()));
    instances.push(Box::new(UNIXProcessFacet::builder().build()));
    instances.push(Box::new(UNIXVolumeFacet::builder().build()));
    instances.push(Box::new(URL::builder().build()));
    instances.push(Box::new(URLFacet::builder().build()));
    instances.push(Box::new(URLHistory::builder().build()));
    instances.push(Box::new(URLHistoryEntry::builder().build()));
    instances.push(Box::new(URLHistoryFacet::builder().build()));
    instances.push(Box::new(URLVisit::builder().build()));
    instances.push(Box::new(URLVisitFacet::builder().build()));
    instances.push(Box::new(UserAccount::builder().build()));
    instances.push(Box::new(UserAccountFacet::builder().build()));
    instances.push(Box::new(UserSession::builder().build()));
    instances.push(Box::new(UserSessionFacet::builder().build()));
    instances.push(Box::new(ValuesEnumeratedEffectFacet::builder().build()));
    instances.push(Box::new(Volume::builder().build()));
    instances.push(Box::new(VolumeFacet::builder().build()));
    instances.push(Box::new(WearableDevice::builder().build()));
    instances.push(Box::new(WebPage::builder().build()));
    instances.push(Box::new(WhoIs::builder().build()));
    instances.push(Box::new(WhoIsFacet::builder().build()));
    instances.push(Box::new(WhoisContactFacet::builder().build()));
    instances.push(Box::new(WhoisRegistrarInfoType::builder().build()));
    instances.push(Box::new(WifiAddress::builder().build()));
    instances.push(Box::new(WifiAddressFacet::builder().build()));
    instances.push(Box::new(Wiki::builder().build()));
    instances.push(Box::new(WikiArticle::builder().build()));
    instances.push(Box::new(WindowsAccount::builder().build()));
    instances.push(Box::new(WindowsAccountFacet::builder().build()));
    instances.push(Box::new(WindowsActiveDirectoryAccount::builder().build()));
    instances.push(Box::new(WindowsActiveDirectoryAccountFacet::builder().build()));
    instances.push(Box::new(WindowsComputerSpecification::builder().build()));
    instances.push(Box::new(WindowsComputerSpecificationFacet::builder().build()));
    instances.push(Box::new(WindowsCriticalSection::builder().build()));
    instances.push(Box::new(WindowsEvent::builder().build()));
    instances.push(Box::new(WindowsFilemapping::builder().build()));
    instances.push(Box::new(WindowsHandle::builder().build()));
    instances.push(Box::new(WindowsHook::builder().build()));
    instances.push(Box::new(WindowsMailslot::builder().build()));
    instances.push(Box::new(WindowsNetworkShare::builder().build()));
    instances.push(Box::new(WindowsPEBinaryFile::builder().build()));
    instances.push(Box::new(WindowsPEBinaryFileFacet::builder().build()));
    instances.push(Box::new(WindowsPEFileHeader::builder().build()));
    instances.push(Box::new(WindowsPEOptionalHeader::builder().build()));
    instances.push(Box::new(WindowsPESection::builder().build()));
    instances.push(Box::new(WindowsPrefetch::builder().build()));
    instances.push(Box::new(WindowsPrefetchFacet::builder().build()));
    instances.push(Box::new(WindowsProcess::builder().build()));
    instances.push(Box::new(WindowsProcessFacet::builder().build()));
    instances.push(Box::new(WindowsRegistryHive::builder().build()));
    instances.push(Box::new(WindowsRegistryHiveFacet::builder().build()));
    instances.push(Box::new(WindowsRegistryKey::builder().build()));
    instances.push(Box::new(WindowsRegistryKeyFacet::builder().build()));
    instances.push(Box::new(WindowsRegistryValue::builder().build()));
    instances.push(Box::new(WindowsService::builder().build()));
    instances.push(Box::new(WindowsServiceFacet::builder().build()));
    instances.push(Box::new(WindowsSystemRestore::builder().build()));
    instances.push(Box::new(WindowsTask::builder().build()));
    instances.push(Box::new(WindowsTaskFacet::builder().build()));
    instances.push(Box::new(WindowsThread::builder().build()));
    instances.push(Box::new(WindowsThreadFacet::builder().build()));
    instances.push(Box::new(WindowsVolumeFacet::builder().build()));
    instances.push(Box::new(WindowsWaitableTime::builder().build()));
    instances.push(Box::new(WirelessNetworkConnection::builder().build()));
    instances.push(Box::new(WirelessNetworkConnectionFacet::builder().build()));
    instances.push(Box::new(WriteBlocker::builder().build()));
    instances.push(Box::new(X509Certificate::builder().build()));
    instances.push(Box::new(X509CertificateFacet::builder().build()));
    instances.push(Box::new(X509V3Certificate::builder().build()));
    instances.push(Box::new(X509V3ExtensionsFacet::builder().build()));
    instances.push(Box::new(LogicalPattern::builder().build()));
    instances.push(Box::new(Pattern::builder().build()));
    instances.push(Box::new(PatternExpression::builder().build()));
    instances.push(Box::new(BenevolentRole::builder().build()));
    instances.push(Box::new(MaliciousRole::builder().build()));
    instances.push(Box::new(NeutralRole::builder().build()));
    instances.push(Box::new(Role::builder().build()));
    instances.push(Box::new(AnalyticTool::builder().build()));
    instances.push(Box::new(BuildFacet::builder().build()));
    instances.push(Box::new(BuildInformationType::builder().build()));
    instances.push(Box::new(BuildUtilityType::builder().build()));
    instances.push(Box::new(CompilerType::builder().build()));
    instances.push(Box::new(ConfiguredTool::builder().build()));
    instances.push(Box::new(DefensiveTool::builder().build()));
    instances.push(Box::new(LibraryType::builder().build()));
    instances.push(Box::new(MaliciousTool::builder().build()));
    instances.push(Box::new(Tool::builder().build()));
    instances.push(Box::new(ControlledDictionary::builder().build()));
    instances.push(Box::new(ControlledDictionaryEntry::builder().build()));
    instances.push(Box::new(Dictionary::builder().build()));
    instances.push(Box::new(DictionaryEntry::builder().build()));
    instances.push(Box::new(Hash::builder().build()));
    instances.push(Box::new(ImproperDictionary::builder().build()));
    instances.push(Box::new(ProperDictionary::builder().build()));
    instances.push(Box::new(Thread::builder().build()));
    instances.push(Box::new(ThreadItem::builder().build()));
    instances.push(Box::new(Victim::builder().build()));
    instances.push(Box::new(VictimTargeting::builder().build()));
    assert_eq!(instances.len(), 426);
}