//! Auto-generated — instantiates every CASE/UCO struct to verify the object model.

use case_uco::graph::CaseGraph;
use case_uco::case::investigation::Attorney;
use case_uco::case::investigation::Authorization;
use case_uco::case::investigation::Examiner;
use case_uco::case::investigation::Investigation;
use case_uco::case::investigation::InvestigativeAction;
use case_uco::case::investigation::Investigator;
use case_uco::case::investigation::ProvenanceRecord;
use case_uco::case::investigation::Subject;
use case_uco::case::investigation::SubjectActionLifecycle;
use case_uco::case::investigation::VictimActionLifecycle;
use case_uco::uco::action::Action;
use case_uco::uco::action::ActionArgumentFacet;
use case_uco::uco::action::ActionEstimationFacet;
use case_uco::uco::action::ActionFrequencyFacet;
use case_uco::uco::action::ActionLifecycle;
use case_uco::uco::action::ActionPattern;
use case_uco::uco::action::ArrayOfAction;
use case_uco::uco::analysis::AnalyticResultFacet;
use case_uco::uco::analysis::ArtifactClassification;
use case_uco::uco::analysis::ArtifactClassificationResultFacet;
use case_uco::uco::configuration::Configuration;
use case_uco::uco::configuration::ConfigurationEntry;
use case_uco::uco::configuration::Dependency;
use case_uco::uco::core::Annotation;
use case_uco::uco::core::Assertion;
use case_uco::uco::core::AttributedName;
use case_uco::uco::core::Bundle;
use case_uco::uco::core::Compilation;
use case_uco::uco::core::ConfidenceFacet;
use case_uco::uco::core::ContextualCompilation;
use case_uco::uco::core::ControlledVocabulary;
use case_uco::uco::core::EnclosingCompilation;
use case_uco::uco::core::Event;
use case_uco::uco::core::ExternalReference;
use case_uco::uco::core::Facet;
use case_uco::uco::core::Grouping;
use case_uco::uco::core::IdentityAbstraction;
use case_uco::uco::core::Item;
use case_uco::uco::core::MarkingDefinitionAbstraction;
use case_uco::uco::core::ModusOperandi;
use case_uco::uco::core::Relationship;
use case_uco::uco::core::UcoInherentCharacterizationThing;
use case_uco::uco::core::UcoObject;
use case_uco::uco::core::UcoThing;
use case_uco::uco::identity::AddressFacet;
use case_uco::uco::identity::AffiliationFacet;
use case_uco::uco::identity::BirthInformationFacet;
use case_uco::uco::identity::CountryOfResidenceFacet;
use case_uco::uco::identity::EventsFacet;
use case_uco::uco::identity::IdentifierFacet;
use case_uco::uco::identity::Identity;
use case_uco::uco::identity::IdentityFacet;
use case_uco::uco::identity::LanguagesFacet;
use case_uco::uco::identity::NationalityFacet;
use case_uco::uco::identity::OccupationFacet;
use case_uco::uco::identity::Organization;
use case_uco::uco::identity::OrganizationDetailsFacet;
use case_uco::uco::identity::Person;
use case_uco::uco::identity::PersonalDetailsFacet;
use case_uco::uco::identity::PhysicalInfoFacet;
use case_uco::uco::identity::QualificationFacet;
use case_uco::uco::identity::RelatedIdentityFacet;
use case_uco::uco::identity::SimpleNameFacet;
use case_uco::uco::identity::VisaFacet;
use case_uco::uco::location::GPSCoordinatesFacet;
use case_uco::uco::location::LatLongCoordinatesFacet;
use case_uco::uco::location::Location;
use case_uco::uco::location::SimpleAddressFacet;
use case_uco::uco::marking::GranularMarking;
use case_uco::uco::marking::LicenseMarking;
use case_uco::uco::marking::MarkingDefinition;
use case_uco::uco::marking::MarkingModel;
use case_uco::uco::marking::ReleaseToMarking;
use case_uco::uco::marking::StatementMarking;
use case_uco::uco::marking::TermsOfUseMarking;
use case_uco::uco::observable::API;
use case_uco::uco::observable::ARPCache;
use case_uco::uco::observable::ARPCacheEntry;
use case_uco::uco::observable::Account;
use case_uco::uco::observable::AccountAuthenticationFacet;
use case_uco::uco::observable::AccountFacet;
use case_uco::uco::observable::Adaptor;
use case_uco::uco::observable::Address;
use case_uco::uco::observable::AlternateDataStream;
use case_uco::uco::observable::AlternateDataStreamFacet;
use case_uco::uco::observable::AndroidDevice;
use case_uco::uco::observable::AndroidDeviceFacet;
use case_uco::uco::observable::AndroidPhone;
use case_uco::uco::observable::AntennaFacet;
use case_uco::uco::observable::AppleDevice;
use case_uco::uco::observable::Appliance;
use case_uco::uco::observable::Application;
use case_uco::uco::observable::ApplicationAccount;
use case_uco::uco::observable::ApplicationAccountFacet;
use case_uco::uco::observable::ApplicationFacet;
use case_uco::uco::observable::ApplicationVersion;
use case_uco::uco::observable::ArchiveFile;
use case_uco::uco::observable::ArchiveFileFacet;
use case_uco::uco::observable::Audio;
use case_uco::uco::observable::AudioFacet;
use case_uco::uco::observable::AutonomousSystem;
use case_uco::uco::observable::AutonomousSystemFacet;
use case_uco::uco::observable::BlackberryPhone;
use case_uco::uco::observable::BlockDeviceNode;
use case_uco::uco::observable::BluetoothAddress;
use case_uco::uco::observable::BluetoothAddressFacet;
use case_uco::uco::observable::BotConfiguration;
use case_uco::uco::observable::BrowserBookmark;
use case_uco::uco::observable::BrowserBookmarkFacet;
use case_uco::uco::observable::BrowserCookie;
use case_uco::uco::observable::BrowserCookieFacet;
use case_uco::uco::observable::Calendar;
use case_uco::uco::observable::CalendarEntry;
use case_uco::uco::observable::CalendarEntryFacet;
use case_uco::uco::observable::CalendarFacet;
use case_uco::uco::observable::Call;
use case_uco::uco::observable::CallFacet;
use case_uco::uco::observable::CapturedTelecommunicationsInformation;
use case_uco::uco::observable::CapturedTelecommunicationsInformationFacet;
use case_uco::uco::observable::CellSite;
use case_uco::uco::observable::CellSiteFacet;
use case_uco::uco::observable::CharacterDeviceNode;
use case_uco::uco::observable::Code;
use case_uco::uco::observable::CompressedStreamFacet;
use case_uco::uco::observable::Computer;
use case_uco::uco::observable::ComputerSpecification;
use case_uco::uco::observable::ComputerSpecificationFacet;
use case_uco::uco::observable::ConfiguredSoftware;
use case_uco::uco::observable::Contact;
use case_uco::uco::observable::ContactAddress;
use case_uco::uco::observable::ContactAffiliation;
use case_uco::uco::observable::ContactEmail;
use case_uco::uco::observable::ContactFacet;
use case_uco::uco::observable::ContactList;
use case_uco::uco::observable::ContactListFacet;
use case_uco::uco::observable::ContactMessaging;
use case_uco::uco::observable::ContactPhone;
use case_uco::uco::observable::ContactProfile;
use case_uco::uco::observable::ContactSIP;
use case_uco::uco::observable::ContactURL;
use case_uco::uco::observable::ContentData;
use case_uco::uco::observable::ContentDataFacet;
use case_uco::uco::observable::CookieHistory;
use case_uco::uco::observable::Credential;
use case_uco::uco::observable::CredentialDump;
use case_uco::uco::observable::DNSCache;
use case_uco::uco::observable::DNSRecord;
use case_uco::uco::observable::DataRangeFacet;
use case_uco::uco::observable::DefinedEffectFacet;
use case_uco::uco::observable::Device;
use case_uco::uco::observable::DeviceFacet;
use case_uco::uco::observable::DigitalAccount;
use case_uco::uco::observable::DigitalAccountFacet;
use case_uco::uco::observable::DigitalAddress;
use case_uco::uco::observable::DigitalAddressFacet;
use case_uco::uco::observable::DigitalCamera;
use case_uco::uco::observable::DigitalSignatureInfo;
use case_uco::uco::observable::DigitalSignatureInfoFacet;
use case_uco::uco::observable::Directory;
use case_uco::uco::observable::Disk;
use case_uco::uco::observable::DiskFacet;
use case_uco::uco::observable::DiskPartition;
use case_uco::uco::observable::DiskPartitionFacet;
use case_uco::uco::observable::DomainName;
use case_uco::uco::observable::DomainNameFacet;
use case_uco::uco::observable::Drone;
use case_uco::uco::observable::EXIFFacet;
use case_uco::uco::observable::EmailAccount;
use case_uco::uco::observable::EmailAccountFacet;
use case_uco::uco::observable::EmailAddress;
use case_uco::uco::observable::EmailAddressFacet;
use case_uco::uco::observable::EmailMessage;
use case_uco::uco::observable::EmailMessageFacet;
use case_uco::uco::observable::EmbeddedDevice;
use case_uco::uco::observable::EncodedStreamFacet;
use case_uco::uco::observable::EncryptedStreamFacet;
use case_uco::uco::observable::EnvironmentVariable;
use case_uco::uco::observable::EventLog;
use case_uco::uco::observable::EventRecord;
use case_uco::uco::observable::EventRecordFacet;
use case_uco::uco::observable::ExtInodeFacet;
use case_uco::uco::observable::ExtractedString;
use case_uco::uco::observable::ExtractedStringsFacet;
use case_uco::uco::observable::File;
use case_uco::uco::observable::FileFacet;
use case_uco::uco::observable::FilePermissionsFacet;
use case_uco::uco::observable::FileSystem;
use case_uco::uco::observable::FileSystemFacet;
use case_uco::uco::observable::FileSystemObject;
use case_uco::uco::observable::ForumPost;
use case_uco::uco::observable::ForumPrivateMessage;
use case_uco::uco::observable::FragmentFacet;
use case_uco::uco::observable::GUI;
use case_uco::uco::observable::GamingConsole;
use case_uco::uco::observable::GenericObservableObject;
use case_uco::uco::observable::GeoLocationEntry;
use case_uco::uco::observable::GeoLocationEntryFacet;
use case_uco::uco::observable::GeoLocationLog;
use case_uco::uco::observable::GeoLocationLogFacet;
use case_uco::uco::observable::GeoLocationTrack;
use case_uco::uco::observable::GeoLocationTrackFacet;
use case_uco::uco::observable::GlobalFlagType;
use case_uco::uco::observable::HTTPConnection;
use case_uco::uco::observable::HTTPConnectionFacet;
use case_uco::uco::observable::Hostname;
use case_uco::uco::observable::ICMPConnection;
use case_uco::uco::observable::ICMPConnectionFacet;
use case_uco::uco::observable::IComHandlerActionType;
use case_uco::uco::observable::IExecActionType;
use case_uco::uco::observable::IPAddress;
use case_uco::uco::observable::IPAddressFacet;
use case_uco::uco::observable::IPNetmask;
use case_uco::uco::observable::IPhone;
use case_uco::uco::observable::IPv4Address;
use case_uco::uco::observable::IPv4AddressFacet;
use case_uco::uco::observable::IPv6Address;
use case_uco::uco::observable::IPv6AddressFacet;
use case_uco::uco::observable::IShowMessageActionType;
use case_uco::uco::observable::Image;
use case_uco::uco::observable::ImageFacet;
use case_uco::uco::observable::InstantMessagingAddress;
use case_uco::uco::observable::InstantMessagingAddressFacet;
use case_uco::uco::observable::Junction;
use case_uco::uco::observable::Laptop;
use case_uco::uco::observable::Library;
use case_uco::uco::observable::LibraryFacet;
use case_uco::uco::observable::MACAddress;
use case_uco::uco::observable::MACAddressFacet;
use case_uco::uco::observable::Memory;
use case_uco::uco::observable::MemoryFacet;
use case_uco::uco::observable::Message;
use case_uco::uco::observable::MessageFacet;
use case_uco::uco::observable::MessageThread;
use case_uco::uco::observable::MessageThreadFacet;
use case_uco::uco::observable::MftRecordFacet;
use case_uco::uco::observable::MimePartType;
use case_uco::uco::observable::MobileAccount;
use case_uco::uco::observable::MobileAccountFacet;
use case_uco::uco::observable::MobileDevice;
use case_uco::uco::observable::MobileDeviceFacet;
use case_uco::uco::observable::MobilePhone;
use case_uco::uco::observable::Mutex;
use case_uco::uco::observable::MutexFacet;
use case_uco::uco::observable::NTFSFile;
use case_uco::uco::observable::NTFSFileFacet;
use case_uco::uco::observable::NTFSFilePermissionsFacet;
use case_uco::uco::observable::NamedPipe;
use case_uco::uco::observable::NetworkAppliance;
use case_uco::uco::observable::NetworkConnection;
use case_uco::uco::observable::NetworkConnectionFacet;
use case_uco::uco::observable::NetworkFlow;
use case_uco::uco::observable::NetworkFlowFacet;
use case_uco::uco::observable::NetworkInterface;
use case_uco::uco::observable::NetworkInterfaceFacet;
use case_uco::uco::observable::NetworkProtocol;
use case_uco::uco::observable::NetworkRoute;
use case_uco::uco::observable::NetworkSubnet;
use case_uco::uco::observable::Note;
use case_uco::uco::observable::NoteFacet;
use case_uco::uco::observable::Observable;
use case_uco::uco::observable::ObservableAction;
use case_uco::uco::observable::ObservableObject;
use case_uco::uco::observable::ObservablePattern;
use case_uco::uco::observable::ObservableRelationship;
use case_uco::uco::observable::Observation;
use case_uco::uco::observable::OnlineService;
use case_uco::uco::observable::OnlineServiceFacet;
use case_uco::uco::observable::OperatingSystem;
use case_uco::uco::observable::OperatingSystemFacet;
use case_uco::uco::observable::PDFFile;
use case_uco::uco::observable::PDFFileFacet;
use case_uco::uco::observable::PathRelationFacet;
use case_uco::uco::observable::PaymentCard;
use case_uco::uco::observable::PhoneAccount;
use case_uco::uco::observable::PhoneAccountFacet;
use case_uco::uco::observable::Pipe;
use case_uco::uco::observable::Post;
use case_uco::uco::observable::Process;
use case_uco::uco::observable::ProcessFacet;
use case_uco::uco::observable::ProcessThread;
use case_uco::uco::observable::Profile;
use case_uco::uco::observable::ProfileFacet;
use case_uco::uco::observable::PropertiesEnumeratedEffectFacet;
use case_uco::uco::observable::PropertyReadEffectFacet;
use case_uco::uco::observable::ProtocolConverter;
use case_uco::uco::observable::RasterPicture;
use case_uco::uco::observable::RasterPictureFacet;
use case_uco::uco::observable::RecoveredObject;
use case_uco::uco::observable::RecoveredObjectFacet;
use case_uco::uco::observable::ReparsePoint;
use case_uco::uco::observable::SIMCard;
use case_uco::uco::observable::SIMCardFacet;
use case_uco::uco::observable::SIPAddress;
use case_uco::uco::observable::SIPAddressFacet;
use case_uco::uco::observable::SMSMessage;
use case_uco::uco::observable::SMSMessageFacet;
use case_uco::uco::observable::SQLiteBlob;
use case_uco::uco::observable::SQLiteBlobFacet;
use case_uco::uco::observable::SecurityAppliance;
use case_uco::uco::observable::Semaphore;
use case_uco::uco::observable::SendControlCodeEffectFacet;
use case_uco::uco::observable::Server;
use case_uco::uco::observable::ShopListing;
use case_uco::uco::observable::SmartDevice;
use case_uco::uco::observable::SmartPhone;
use case_uco::uco::observable::Snapshot;
use case_uco::uco::observable::Socket;
use case_uco::uco::observable::SocketAddress;
use case_uco::uco::observable::Software;
use case_uco::uco::observable::SoftwareFacet;
use case_uco::uco::observable::StateChangeEffectFacet;
use case_uco::uco::observable::StorageMedium;
use case_uco::uco::observable::StorageMediumFacet;
use case_uco::uco::observable::SymbolicLink;
use case_uco::uco::observable::SymbolicLinkFacet;
use case_uco::uco::observable::TCPConnection;
use case_uco::uco::observable::TCPConnectionFacet;
use case_uco::uco::observable::TableField;
use case_uco::uco::observable::TableFieldFacet;
use case_uco::uco::observable::Tablet;
use case_uco::uco::observable::TaskActionType;
use case_uco::uco::observable::TriggerType;
use case_uco::uco::observable::Tweet;
use case_uco::uco::observable::TwitterProfileFacet;
use case_uco::uco::observable::UNIXAccount;
use case_uco::uco::observable::UNIXAccountFacet;
use case_uco::uco::observable::UNIXFile;
use case_uco::uco::observable::UNIXFilePermissionsFacet;
use case_uco::uco::observable::UNIXProcess;
use case_uco::uco::observable::UNIXProcessFacet;
use case_uco::uco::observable::UNIXVolumeFacet;
use case_uco::uco::observable::URL;
use case_uco::uco::observable::URLFacet;
use case_uco::uco::observable::URLHistory;
use case_uco::uco::observable::URLHistoryEntry;
use case_uco::uco::observable::URLHistoryFacet;
use case_uco::uco::observable::URLVisit;
use case_uco::uco::observable::URLVisitFacet;
use case_uco::uco::observable::UserAccount;
use case_uco::uco::observable::UserAccountFacet;
use case_uco::uco::observable::UserSession;
use case_uco::uco::observable::UserSessionFacet;
use case_uco::uco::observable::ValuesEnumeratedEffectFacet;
use case_uco::uco::observable::Volume;
use case_uco::uco::observable::VolumeFacet;
use case_uco::uco::observable::WearableDevice;
use case_uco::uco::observable::WebPage;
use case_uco::uco::observable::WhoIs;
use case_uco::uco::observable::WhoIsFacet;
use case_uco::uco::observable::WhoisContactFacet;
use case_uco::uco::observable::WhoisRegistrarInfoType;
use case_uco::uco::observable::WifiAddress;
use case_uco::uco::observable::WifiAddressFacet;
use case_uco::uco::observable::Wiki;
use case_uco::uco::observable::WikiArticle;
use case_uco::uco::observable::WindowsAccount;
use case_uco::uco::observable::WindowsAccountFacet;
use case_uco::uco::observable::WindowsActiveDirectoryAccount;
use case_uco::uco::observable::WindowsActiveDirectoryAccountFacet;
use case_uco::uco::observable::WindowsComputerSpecification;
use case_uco::uco::observable::WindowsComputerSpecificationFacet;
use case_uco::uco::observable::WindowsCriticalSection;
use case_uco::uco::observable::WindowsEvent;
use case_uco::uco::observable::WindowsFilemapping;
use case_uco::uco::observable::WindowsHandle;
use case_uco::uco::observable::WindowsHook;
use case_uco::uco::observable::WindowsMailslot;
use case_uco::uco::observable::WindowsNetworkShare;
use case_uco::uco::observable::WindowsPEBinaryFile;
use case_uco::uco::observable::WindowsPEBinaryFileFacet;
use case_uco::uco::observable::WindowsPEFileHeader;
use case_uco::uco::observable::WindowsPEOptionalHeader;
use case_uco::uco::observable::WindowsPESection;
use case_uco::uco::observable::WindowsPrefetch;
use case_uco::uco::observable::WindowsPrefetchFacet;
use case_uco::uco::observable::WindowsProcess;
use case_uco::uco::observable::WindowsProcessFacet;
use case_uco::uco::observable::WindowsRegistryHive;
use case_uco::uco::observable::WindowsRegistryHiveFacet;
use case_uco::uco::observable::WindowsRegistryKey;
use case_uco::uco::observable::WindowsRegistryKeyFacet;
use case_uco::uco::observable::WindowsRegistryValue;
use case_uco::uco::observable::WindowsService;
use case_uco::uco::observable::WindowsServiceFacet;
use case_uco::uco::observable::WindowsSystemRestore;
use case_uco::uco::observable::WindowsTask;
use case_uco::uco::observable::WindowsTaskFacet;
use case_uco::uco::observable::WindowsThread;
use case_uco::uco::observable::WindowsThreadFacet;
use case_uco::uco::observable::WindowsVolumeFacet;
use case_uco::uco::observable::WindowsWaitableTime;
use case_uco::uco::observable::WirelessNetworkConnection;
use case_uco::uco::observable::WirelessNetworkConnectionFacet;
use case_uco::uco::observable::WriteBlocker;
use case_uco::uco::observable::X509Certificate;
use case_uco::uco::observable::X509CertificateFacet;
use case_uco::uco::observable::X509V3Certificate;
use case_uco::uco::observable::X509V3ExtensionsFacet;
use case_uco::uco::pattern::LogicalPattern;
use case_uco::uco::pattern::Pattern;
use case_uco::uco::pattern::PatternExpression;
use case_uco::uco::role::BenevolentRole;
use case_uco::uco::role::MaliciousRole;
use case_uco::uco::role::NeutralRole;
use case_uco::uco::role::Role;
use case_uco::uco::tool::AnalyticTool;
use case_uco::uco::tool::BuildFacet;
use case_uco::uco::tool::BuildInformationType;
use case_uco::uco::tool::BuildUtilityType;
use case_uco::uco::tool::CompilerType;
use case_uco::uco::tool::ConfiguredTool;
use case_uco::uco::tool::DefensiveTool;
use case_uco::uco::tool::LibraryType;
use case_uco::uco::tool::MaliciousTool;
use case_uco::uco::tool::Tool;
use case_uco::uco::types::ControlledDictionary;
use case_uco::uco::types::ControlledDictionaryEntry;
use case_uco::uco::types::Dictionary;
use case_uco::uco::types::DictionaryEntry;
use case_uco::uco::types::Hash;
use case_uco::uco::types::ImproperDictionary;
use case_uco::uco::types::ProperDictionary;
use case_uco::uco::types::Thread;
use case_uco::uco::types::ThreadItem;
use case_uco::uco::victim::Victim;
use case_uco::uco::victim::VictimTargeting;

#[test]
fn test_all_classes_can_be_instantiated() {
    let mut graph = CaseGraph::new("http://example.org/kb/");
    graph.create(&Attorney::builder().build());
    graph.create(&Authorization::builder().build());
    graph.create(&Examiner::builder().build());
    graph.create(&Investigation::builder().build());
    graph.create(&InvestigativeAction::builder().build());
    graph.create(&Investigator::builder().build());
    graph.create(&ProvenanceRecord::builder().build());
    graph.create(&Subject::builder().build());
    graph.create(&SubjectActionLifecycle::builder().build());
    graph.create(&VictimActionLifecycle::builder().build());
    graph.create(&Action::builder().build());
    graph.create(&ActionArgumentFacet::builder().build());
    graph.create(&ActionEstimationFacet::builder().build());
    graph.create(&ActionFrequencyFacet::builder().build());
    graph.create(&ActionLifecycle::builder().build());
    graph.create(&ActionPattern::builder().build());
    graph.create(&ArrayOfAction::builder().build());
    graph.create(&AnalyticResultFacet::builder().build());
    graph.create(&ArtifactClassification::builder().build());
    graph.create(&ArtifactClassificationResultFacet::builder().build());
    graph.create(&Configuration::builder().build());
    graph.create(&ConfigurationEntry::builder().build());
    graph.create(&Dependency::builder().build());
    graph.create(&Annotation::builder().build());
    graph.create(&Assertion::builder().build());
    graph.create(&AttributedName::builder().build());
    graph.create(&Bundle::builder().build());
    graph.create(&Compilation::builder().build());
    graph.create(&ConfidenceFacet::builder().build());
    graph.create(&ContextualCompilation::builder().build());
    graph.create(&ControlledVocabulary::builder().build());
    graph.create(&EnclosingCompilation::builder().build());
    graph.create(&Event::builder().build());
    graph.create(&ExternalReference::builder().build());
    graph.create(&Facet::builder().build());
    graph.create(&Grouping::builder().build());
    graph.create(&IdentityAbstraction::builder().build());
    graph.create(&Item::builder().build());
    graph.create(&MarkingDefinitionAbstraction::builder().build());
    graph.create(&ModusOperandi::builder().build());
    graph.create(&Relationship::builder().build());
    graph.create(&UcoInherentCharacterizationThing::builder().build());
    graph.create(&UcoObject::builder().build());
    graph.create(&UcoThing::builder().build());
    graph.create(&AddressFacet::builder().build());
    graph.create(&AffiliationFacet::builder().build());
    graph.create(&BirthInformationFacet::builder().build());
    graph.create(&CountryOfResidenceFacet::builder().build());
    graph.create(&EventsFacet::builder().build());
    graph.create(&IdentifierFacet::builder().build());
    graph.create(&Identity::builder().build());
    graph.create(&IdentityFacet::builder().build());
    graph.create(&LanguagesFacet::builder().build());
    graph.create(&NationalityFacet::builder().build());
    graph.create(&OccupationFacet::builder().build());
    graph.create(&Organization::builder().build());
    graph.create(&OrganizationDetailsFacet::builder().build());
    graph.create(&Person::builder().build());
    graph.create(&PersonalDetailsFacet::builder().build());
    graph.create(&PhysicalInfoFacet::builder().build());
    graph.create(&QualificationFacet::builder().build());
    graph.create(&RelatedIdentityFacet::builder().build());
    graph.create(&SimpleNameFacet::builder().build());
    graph.create(&VisaFacet::builder().build());
    graph.create(&GPSCoordinatesFacet::builder().build());
    graph.create(&LatLongCoordinatesFacet::builder().build());
    graph.create(&Location::builder().build());
    graph.create(&SimpleAddressFacet::builder().build());
    graph.create(&GranularMarking::builder().build());
    graph.create(&LicenseMarking::builder().build());
    graph.create(&MarkingDefinition::builder().build());
    graph.create(&MarkingModel::builder().build());
    graph.create(&ReleaseToMarking::builder().build());
    graph.create(&StatementMarking::builder().build());
    graph.create(&TermsOfUseMarking::builder().build());
    graph.create(&API::builder().build());
    graph.create(&ARPCache::builder().build());
    graph.create(&ARPCacheEntry::builder().build());
    graph.create(&Account::builder().build());
    graph.create(&AccountAuthenticationFacet::builder().build());
    graph.create(&AccountFacet::builder().build());
    graph.create(&Adaptor::builder().build());
    graph.create(&Address::builder().build());
    graph.create(&AlternateDataStream::builder().build());
    graph.create(&AlternateDataStreamFacet::builder().build());
    graph.create(&AndroidDevice::builder().build());
    graph.create(&AndroidDeviceFacet::builder().build());
    graph.create(&AndroidPhone::builder().build());
    graph.create(&AntennaFacet::builder().build());
    graph.create(&AppleDevice::builder().build());
    graph.create(&Appliance::builder().build());
    graph.create(&Application::builder().build());
    graph.create(&ApplicationAccount::builder().build());
    graph.create(&ApplicationAccountFacet::builder().build());
    graph.create(&ApplicationFacet::builder().build());
    graph.create(&ApplicationVersion::builder().build());
    graph.create(&ArchiveFile::builder().build());
    graph.create(&ArchiveFileFacet::builder().build());
    graph.create(&Audio::builder().build());
    graph.create(&AudioFacet::builder().build());
    graph.create(&AutonomousSystem::builder().build());
    graph.create(&AutonomousSystemFacet::builder().build());
    graph.create(&BlackberryPhone::builder().build());
    graph.create(&BlockDeviceNode::builder().build());
    graph.create(&BluetoothAddress::builder().build());
    graph.create(&BluetoothAddressFacet::builder().build());
    graph.create(&BotConfiguration::builder().build());
    graph.create(&BrowserBookmark::builder().build());
    graph.create(&BrowserBookmarkFacet::builder().build());
    graph.create(&BrowserCookie::builder().build());
    graph.create(&BrowserCookieFacet::builder().build());
    graph.create(&Calendar::builder().build());
    graph.create(&CalendarEntry::builder().build());
    graph.create(&CalendarEntryFacet::builder().build());
    graph.create(&CalendarFacet::builder().build());
    graph.create(&Call::builder().build());
    graph.create(&CallFacet::builder().build());
    graph.create(&CapturedTelecommunicationsInformation::builder().build());
    graph.create(&CapturedTelecommunicationsInformationFacet::builder().build());
    graph.create(&CellSite::builder().build());
    graph.create(&CellSiteFacet::builder().build());
    graph.create(&CharacterDeviceNode::builder().build());
    graph.create(&Code::builder().build());
    graph.create(&CompressedStreamFacet::builder().build());
    graph.create(&Computer::builder().build());
    graph.create(&ComputerSpecification::builder().build());
    graph.create(&ComputerSpecificationFacet::builder().build());
    graph.create(&ConfiguredSoftware::builder().build());
    graph.create(&Contact::builder().build());
    graph.create(&ContactAddress::builder().build());
    graph.create(&ContactAffiliation::builder().build());
    graph.create(&ContactEmail::builder().build());
    graph.create(&ContactFacet::builder().build());
    graph.create(&ContactList::builder().build());
    graph.create(&ContactListFacet::builder().build());
    graph.create(&ContactMessaging::builder().build());
    graph.create(&ContactPhone::builder().build());
    graph.create(&ContactProfile::builder().build());
    graph.create(&ContactSIP::builder().build());
    graph.create(&ContactURL::builder().build());
    graph.create(&ContentData::builder().build());
    graph.create(&ContentDataFacet::builder().build());
    graph.create(&CookieHistory::builder().build());
    graph.create(&Credential::builder().build());
    graph.create(&CredentialDump::builder().build());
    graph.create(&DNSCache::builder().build());
    graph.create(&DNSRecord::builder().build());
    graph.create(&DataRangeFacet::builder().build());
    graph.create(&DefinedEffectFacet::builder().build());
    graph.create(&Device::builder().build());
    graph.create(&DeviceFacet::builder().build());
    graph.create(&DigitalAccount::builder().build());
    graph.create(&DigitalAccountFacet::builder().build());
    graph.create(&DigitalAddress::builder().build());
    graph.create(&DigitalAddressFacet::builder().build());
    graph.create(&DigitalCamera::builder().build());
    graph.create(&DigitalSignatureInfo::builder().build());
    graph.create(&DigitalSignatureInfoFacet::builder().build());
    graph.create(&Directory::builder().build());
    graph.create(&Disk::builder().build());
    graph.create(&DiskFacet::builder().build());
    graph.create(&DiskPartition::builder().build());
    graph.create(&DiskPartitionFacet::builder().build());
    graph.create(&DomainName::builder().build());
    graph.create(&DomainNameFacet::builder().build());
    graph.create(&Drone::builder().build());
    graph.create(&EXIFFacet::builder().build());
    graph.create(&EmailAccount::builder().build());
    graph.create(&EmailAccountFacet::builder().build());
    graph.create(&EmailAddress::builder().build());
    graph.create(&EmailAddressFacet::builder().build());
    graph.create(&EmailMessage::builder().build());
    graph.create(&EmailMessageFacet::builder().build());
    graph.create(&EmbeddedDevice::builder().build());
    graph.create(&EncodedStreamFacet::builder().build());
    graph.create(&EncryptedStreamFacet::builder().build());
    graph.create(&EnvironmentVariable::builder().build());
    graph.create(&EventLog::builder().build());
    graph.create(&EventRecord::builder().build());
    graph.create(&EventRecordFacet::builder().build());
    graph.create(&ExtInodeFacet::builder().build());
    graph.create(&ExtractedString::builder().build());
    graph.create(&ExtractedStringsFacet::builder().build());
    graph.create(&File::builder().build());
    graph.create(&FileFacet::builder().build());
    graph.create(&FilePermissionsFacet::builder().build());
    graph.create(&FileSystem::builder().build());
    graph.create(&FileSystemFacet::builder().build());
    graph.create(&FileSystemObject::builder().build());
    graph.create(&ForumPost::builder().build());
    graph.create(&ForumPrivateMessage::builder().build());
    graph.create(&FragmentFacet::builder().build());
    graph.create(&GUI::builder().build());
    graph.create(&GamingConsole::builder().build());
    graph.create(&GenericObservableObject::builder().build());
    graph.create(&GeoLocationEntry::builder().build());
    graph.create(&GeoLocationEntryFacet::builder().build());
    graph.create(&GeoLocationLog::builder().build());
    graph.create(&GeoLocationLogFacet::builder().build());
    graph.create(&GeoLocationTrack::builder().build());
    graph.create(&GeoLocationTrackFacet::builder().build());
    graph.create(&GlobalFlagType::builder().build());
    graph.create(&HTTPConnection::builder().build());
    graph.create(&HTTPConnectionFacet::builder().build());
    graph.create(&Hostname::builder().build());
    graph.create(&ICMPConnection::builder().build());
    graph.create(&ICMPConnectionFacet::builder().build());
    graph.create(&IComHandlerActionType::builder().build());
    graph.create(&IExecActionType::builder().build());
    graph.create(&IPAddress::builder().build());
    graph.create(&IPAddressFacet::builder().build());
    graph.create(&IPNetmask::builder().build());
    graph.create(&IPhone::builder().build());
    graph.create(&IPv4Address::builder().build());
    graph.create(&IPv4AddressFacet::builder().build());
    graph.create(&IPv6Address::builder().build());
    graph.create(&IPv6AddressFacet::builder().build());
    graph.create(&IShowMessageActionType::builder().build());
    graph.create(&Image::builder().build());
    graph.create(&ImageFacet::builder().build());
    graph.create(&InstantMessagingAddress::builder().build());
    graph.create(&InstantMessagingAddressFacet::builder().build());
    graph.create(&Junction::builder().build());
    graph.create(&Laptop::builder().build());
    graph.create(&Library::builder().build());
    graph.create(&LibraryFacet::builder().build());
    graph.create(&MACAddress::builder().build());
    graph.create(&MACAddressFacet::builder().build());
    graph.create(&Memory::builder().build());
    graph.create(&MemoryFacet::builder().build());
    graph.create(&Message::builder().build());
    graph.create(&MessageFacet::builder().build());
    graph.create(&MessageThread::builder().build());
    graph.create(&MessageThreadFacet::builder().build());
    graph.create(&MftRecordFacet::builder().build());
    graph.create(&MimePartType::builder().build());
    graph.create(&MobileAccount::builder().build());
    graph.create(&MobileAccountFacet::builder().build());
    graph.create(&MobileDevice::builder().build());
    graph.create(&MobileDeviceFacet::builder().build());
    graph.create(&MobilePhone::builder().build());
    graph.create(&Mutex::builder().build());
    graph.create(&MutexFacet::builder().build());
    graph.create(&NTFSFile::builder().build());
    graph.create(&NTFSFileFacet::builder().build());
    graph.create(&NTFSFilePermissionsFacet::builder().build());
    graph.create(&NamedPipe::builder().build());
    graph.create(&NetworkAppliance::builder().build());
    graph.create(&NetworkConnection::builder().build());
    graph.create(&NetworkConnectionFacet::builder().build());
    graph.create(&NetworkFlow::builder().build());
    graph.create(&NetworkFlowFacet::builder().build());
    graph.create(&NetworkInterface::builder().build());
    graph.create(&NetworkInterfaceFacet::builder().build());
    graph.create(&NetworkProtocol::builder().build());
    graph.create(&NetworkRoute::builder().build());
    graph.create(&NetworkSubnet::builder().build());
    graph.create(&Note::builder().build());
    graph.create(&NoteFacet::builder().build());
    graph.create(&Observable::builder().build());
    graph.create(&ObservableAction::builder().build());
    graph.create(&ObservableObject::builder().build());
    graph.create(&ObservablePattern::builder().build());
    graph.create(&ObservableRelationship::builder().build());
    graph.create(&Observation::builder().build());
    graph.create(&OnlineService::builder().build());
    graph.create(&OnlineServiceFacet::builder().build());
    graph.create(&OperatingSystem::builder().build());
    graph.create(&OperatingSystemFacet::builder().build());
    graph.create(&PDFFile::builder().build());
    graph.create(&PDFFileFacet::builder().build());
    graph.create(&PathRelationFacet::builder().build());
    graph.create(&PaymentCard::builder().build());
    graph.create(&PhoneAccount::builder().build());
    graph.create(&PhoneAccountFacet::builder().build());
    graph.create(&Pipe::builder().build());
    graph.create(&Post::builder().build());
    graph.create(&Process::builder().build());
    graph.create(&ProcessFacet::builder().build());
    graph.create(&ProcessThread::builder().build());
    graph.create(&Profile::builder().build());
    graph.create(&ProfileFacet::builder().build());
    graph.create(&PropertiesEnumeratedEffectFacet::builder().build());
    graph.create(&PropertyReadEffectFacet::builder().build());
    graph.create(&ProtocolConverter::builder().build());
    graph.create(&RasterPicture::builder().build());
    graph.create(&RasterPictureFacet::builder().build());
    graph.create(&RecoveredObject::builder().build());
    graph.create(&RecoveredObjectFacet::builder().build());
    graph.create(&ReparsePoint::builder().build());
    graph.create(&SIMCard::builder().build());
    graph.create(&SIMCardFacet::builder().build());
    graph.create(&SIPAddress::builder().build());
    graph.create(&SIPAddressFacet::builder().build());
    graph.create(&SMSMessage::builder().build());
    graph.create(&SMSMessageFacet::builder().build());
    graph.create(&SQLiteBlob::builder().build());
    graph.create(&SQLiteBlobFacet::builder().build());
    graph.create(&SecurityAppliance::builder().build());
    graph.create(&Semaphore::builder().build());
    graph.create(&SendControlCodeEffectFacet::builder().build());
    graph.create(&Server::builder().build());
    graph.create(&ShopListing::builder().build());
    graph.create(&SmartDevice::builder().build());
    graph.create(&SmartPhone::builder().build());
    graph.create(&Snapshot::builder().build());
    graph.create(&Socket::builder().build());
    graph.create(&SocketAddress::builder().build());
    graph.create(&Software::builder().build());
    graph.create(&SoftwareFacet::builder().build());
    graph.create(&StateChangeEffectFacet::builder().build());
    graph.create(&StorageMedium::builder().build());
    graph.create(&StorageMediumFacet::builder().build());
    graph.create(&SymbolicLink::builder().build());
    graph.create(&SymbolicLinkFacet::builder().build());
    graph.create(&TCPConnection::builder().build());
    graph.create(&TCPConnectionFacet::builder().build());
    graph.create(&TableField::builder().build());
    graph.create(&TableFieldFacet::builder().build());
    graph.create(&Tablet::builder().build());
    graph.create(&TaskActionType::builder().build());
    graph.create(&TriggerType::builder().build());
    graph.create(&Tweet::builder().build());
    graph.create(&TwitterProfileFacet::builder().build());
    graph.create(&UNIXAccount::builder().build());
    graph.create(&UNIXAccountFacet::builder().build());
    graph.create(&UNIXFile::builder().build());
    graph.create(&UNIXFilePermissionsFacet::builder().build());
    graph.create(&UNIXProcess::builder().build());
    graph.create(&UNIXProcessFacet::builder().build());
    graph.create(&UNIXVolumeFacet::builder().build());
    graph.create(&URL::builder().build());
    graph.create(&URLFacet::builder().build());
    graph.create(&URLHistory::builder().build());
    graph.create(&URLHistoryEntry::builder().build());
    graph.create(&URLHistoryFacet::builder().build());
    graph.create(&URLVisit::builder().build());
    graph.create(&URLVisitFacet::builder().build());
    graph.create(&UserAccount::builder().build());
    graph.create(&UserAccountFacet::builder().build());
    graph.create(&UserSession::builder().build());
    graph.create(&UserSessionFacet::builder().build());
    graph.create(&ValuesEnumeratedEffectFacet::builder().build());
    graph.create(&Volume::builder().build());
    graph.create(&VolumeFacet::builder().build());
    graph.create(&WearableDevice::builder().build());
    graph.create(&WebPage::builder().build());
    graph.create(&WhoIs::builder().build());
    graph.create(&WhoIsFacet::builder().build());
    graph.create(&WhoisContactFacet::builder().build());
    graph.create(&WhoisRegistrarInfoType::builder().build());
    graph.create(&WifiAddress::builder().build());
    graph.create(&WifiAddressFacet::builder().build());
    graph.create(&Wiki::builder().build());
    graph.create(&WikiArticle::builder().build());
    graph.create(&WindowsAccount::builder().build());
    graph.create(&WindowsAccountFacet::builder().build());
    graph.create(&WindowsActiveDirectoryAccount::builder().build());
    graph.create(&WindowsActiveDirectoryAccountFacet::builder().build());
    graph.create(&WindowsComputerSpecification::builder().build());
    graph.create(&WindowsComputerSpecificationFacet::builder().build());
    graph.create(&WindowsCriticalSection::builder().build());
    graph.create(&WindowsEvent::builder().build());
    graph.create(&WindowsFilemapping::builder().build());
    graph.create(&WindowsHandle::builder().build());
    graph.create(&WindowsHook::builder().build());
    graph.create(&WindowsMailslot::builder().build());
    graph.create(&WindowsNetworkShare::builder().build());
    graph.create(&WindowsPEBinaryFile::builder().build());
    graph.create(&WindowsPEBinaryFileFacet::builder().build());
    graph.create(&WindowsPEFileHeader::builder().build());
    graph.create(&WindowsPEOptionalHeader::builder().build());
    graph.create(&WindowsPESection::builder().build());
    graph.create(&WindowsPrefetch::builder().build());
    graph.create(&WindowsPrefetchFacet::builder().build());
    graph.create(&WindowsProcess::builder().build());
    graph.create(&WindowsProcessFacet::builder().build());
    graph.create(&WindowsRegistryHive::builder().build());
    graph.create(&WindowsRegistryHiveFacet::builder().build());
    graph.create(&WindowsRegistryKey::builder().build());
    graph.create(&WindowsRegistryKeyFacet::builder().build());
    graph.create(&WindowsRegistryValue::builder().build());
    graph.create(&WindowsService::builder().build());
    graph.create(&WindowsServiceFacet::builder().build());
    graph.create(&WindowsSystemRestore::builder().build());
    graph.create(&WindowsTask::builder().build());
    graph.create(&WindowsTaskFacet::builder().build());
    graph.create(&WindowsThread::builder().build());
    graph.create(&WindowsThreadFacet::builder().build());
    graph.create(&WindowsVolumeFacet::builder().build());
    graph.create(&WindowsWaitableTime::builder().build());
    graph.create(&WirelessNetworkConnection::builder().build());
    graph.create(&WirelessNetworkConnectionFacet::builder().build());
    graph.create(&WriteBlocker::builder().build());
    graph.create(&X509Certificate::builder().build());
    graph.create(&X509CertificateFacet::builder().build());
    graph.create(&X509V3Certificate::builder().build());
    graph.create(&X509V3ExtensionsFacet::builder().build());
    graph.create(&LogicalPattern::builder().build());
    graph.create(&Pattern::builder().build());
    graph.create(&PatternExpression::builder().build());
    graph.create(&BenevolentRole::builder().build());
    graph.create(&MaliciousRole::builder().build());
    graph.create(&NeutralRole::builder().build());
    graph.create(&Role::builder().build());
    graph.create(&AnalyticTool::builder().build());
    graph.create(&BuildFacet::builder().build());
    graph.create(&BuildInformationType::builder().build());
    graph.create(&BuildUtilityType::builder().build());
    graph.create(&CompilerType::builder().build());
    graph.create(&ConfiguredTool::builder().build());
    graph.create(&DefensiveTool::builder().build());
    graph.create(&LibraryType::builder().build());
    graph.create(&MaliciousTool::builder().build());
    graph.create(&Tool::builder().build());
    graph.create(&ControlledDictionary::builder().build());
    graph.create(&ControlledDictionaryEntry::builder().build());
    graph.create(&Dictionary::builder().build());
    graph.create(&DictionaryEntry::builder().build());
    graph.create(&Hash::builder().build());
    graph.create(&ImproperDictionary::builder().build());
    graph.create(&ProperDictionary::builder().build());
    graph.create(&Thread::builder().build());
    graph.create(&ThreadItem::builder().build());
    graph.create(&Victim::builder().build());
    graph.create(&VictimTargeting::builder().build());
    assert_eq!(graph.len(), 426);
}